In [1]:
import numpy as np

In [2]:
data = np.arange(12).reshape(3,4)

In [3]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
type(data)

numpy.ndarray

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 4)

In [7]:
data.size

12

In [8]:
data.dtype

dtype('int64')

In [9]:
import numpy as np

In [10]:
data1 = np.array([1,2,3])

In [11]:
data1

array([1, 2, 3])

In [13]:
data2 = np.array([[1,2,3],[4,5,6]])

In [15]:
data2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.empty((5,2))

array([[6.93136691e-310, 6.93136691e-310],
       [6.93136691e-310, 6.93136691e-310],
       [6.93136691e-310, 6.93136691e-310],
       [6.93136691e-310, 6.93136691e-310],
       [6.93136691e-310, 2.42092166e-322]])

In [19]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [20]:
np.array([1,2,3,4],float)

array([1., 2., 3., 4.])

In [21]:
np.ones((2,3),dtype='float64')

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
data_one = np.array([[1,2,3],[4,5,6]])

In [26]:
data_one.dtype.name

'int64'

In [27]:
data = np.array([[1,2,3],[4,5,6]])

In [28]:
data.dtype

dtype('int64')

In [29]:
float_data = data.astype(np.float64)

In [30]:
float_data.dtype

dtype('float64')

In [31]:
float_data = np.array([1.2,2.3,3.5])

In [32]:
float_data

array([1.2, 2.3, 3.5])

In [33]:
int_data = float_data.astype(np.int64)

In [34]:
int_data

array([1, 2, 3])

In [35]:
str_data = np.array(['1','2','3'])

In [36]:
int_data = str_data.astype(np.int64)

In [37]:
int_data

array([1, 2, 3])

In [38]:
import numpy as np

In [39]:
data1 = np.array([[1,2,3],[4,5,6]])

In [40]:
data2 = np.array([[1,2,3],[4,5,6]])

In [41]:
data1+data2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [42]:
data1*data2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [43]:
data1-data2

array([[0, 0, 0],
       [0, 0, 0]])

In [44]:
data1/data2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
import numpy as np

In [46]:
arr1 = np.array([[0],[1],[2],[3]])

In [47]:
arr1.shape

(4, 1)

In [48]:
arr2 = np.array([1,2,3])

In [49]:
arr2.shape

(3,)

In [50]:
arr1+arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [51]:
import numpy as np

In [52]:
data1 = np.array([[1,2,3],[4,5,6]])

In [53]:
data2 = 10

In [54]:
data1+data2

array([[11, 12, 13],
       [14, 15, 16]])

In [55]:
data1*data2

array([[10, 20, 30],
       [40, 50, 60]])

In [57]:
data1-data2

array([[-9, -8, -7],
       [-6, -5, -4]])

In [58]:
data1/data2

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [59]:
import numpy as np

In [60]:
arr = np.arange(8)

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [62]:
arr[5]

5

In [63]:
arr[3:5]

array([3, 4])

In [64]:
arr[1:6:2]

array([1, 3, 5])

In [65]:
import numpy as np

In [66]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [67]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr2d[1]

array([4, 5, 6])

In [69]:
arr2d[0,1]

2

In [70]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr2d[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [74]:
arr2d[1,:2]

array([4, 5])

In [1]:
import numpy as np

In [2]:
demo_arr = np.empty((4,4))
for i in range(4):
    demo_arr[i] = np.arange(i,i+4)

In [3]:
demo_arr

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [4]:
demo_arr[[0,2]]

array([[0., 1., 2., 3.],
       [2., 3., 4., 5.]])

In [5]:
demo_arr[[1,3],[1,2]]

array([2., 5.])

In [14]:
student_name = np.array(['Tom','Lily','Jack','Rose'])

In [15]:
student_name

array(['Tom', 'Lily', 'Jack', 'Rose'], dtype='<U4')

In [9]:
student_score = np.array([[79,88,90],[89,90,92],[83,78,85],[78,76,80]])

In [10]:
student_score

array([[79, 88, 90],
       [89, 90, 92],
       [83, 78, 85],
       [78, 76, 80]])

In [16]:
student_name=='Jack'

array([False, False,  True, False])

In [17]:
student_score[student_name=='Jack']

array([[83, 78, 85]])

In [18]:
student_score[student_name=='Jack',:1]

array([[83]])

In [19]:
arr = np.arange(12).reshape(3,4)

In [20]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [22]:
arr = np.arange(16).reshape((2,2,4))

In [23]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [24]:
arr.shape

(2, 2, 4)

In [25]:
arr.transpose(1,2,0)

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [26]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [27]:
arr.swapaxes(1,0)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [28]:
arr = np.array([4,9,16])

In [29]:
np.sqrt(arr)

array([2., 3., 4.])

In [30]:
np.abs(arr)

array([ 4,  9, 16])

In [31]:
np.square(arr)

array([ 16,  81, 256])

In [32]:
x = np.array([12,9,13,15])

In [33]:
y = np.array([11,10,4,8])

In [34]:
np.add(x,y)

array([23, 19, 17, 23])

In [35]:
np.multiply(x,y)

array([132,  90,  52, 120])

In [36]:
np.maximum(x,y)

array([12, 10, 13, 15])

In [37]:
np.minimum(x,y)

array([11,  9,  4,  8])

In [38]:
np.greater(x,y)

array([ True, False,  True,  True])

In [39]:
arr_x = np.array([1,5,7])

In [40]:
arr_y = np.array([2,6,8])

In [41]:
arr_con = np.array([True,False,True])

In [42]:
result = np.where(arr_con,arr_x,arr_y)

In [43]:
result

array([1, 6, 7])

In [44]:
arr = np.arange(10)

In [45]:
arr.sum()

45

In [46]:
arr.mean()

4.5

In [47]:
arr.min()

0

In [48]:
arr.max()

9

In [49]:
arr.argmax()

9

In [50]:
arr.argmin()

0

In [51]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [52]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
arr = np.array([[6,2,7],[3,6,2],[4,3,2]])

In [54]:
arr

array([[6, 2, 7],
       [3, 6, 2],
       [4, 3, 2]])

In [55]:
arr.sort()

In [56]:
arr

array([[2, 6, 7],
       [2, 3, 6],
       [2, 3, 4]])

In [57]:
arr = np.array([[6,2,7],[3,6,2],[4,3,2]])

In [58]:
arr

array([[6, 2, 7],
       [3, 6, 2],
       [4, 3, 2]])

In [59]:
arr.sort(0)

In [60]:
arr

array([[3, 2, 2],
       [4, 3, 2],
       [6, 6, 7]])

In [61]:
arr = np.array([[1,-2,-7],[-3,6,2],[-4,3,2]])

In [62]:
arr

array([[ 1, -2, -7],
       [-3,  6,  2],
       [-4,  3,  2]])

In [63]:
np.any(arr>0)

True

In [64]:
np.all(arr>0)

False

In [65]:
arr = np.array([12,11,34,23,12,8,11])

In [66]:
np.unique(arr)

array([ 8, 11, 12, 23, 34])

In [67]:
np.in1d(arr,[11,12])

array([ True,  True, False, False,  True, False,  True])

In [68]:
arr_x = np.array([[1,2,3],[4,5,6]])

In [69]:
arr_y = np.array([[1,2],[3,4],[5,6]])

In [70]:
arr_x.dot(arr_y)

array([[22, 28],
       [49, 64]])

In [71]:
import numpy as np

In [72]:
np.random.rand(3,3)

array([[0.30582276, 0.755727  , 0.03394792],
       [0.62952958, 0.61407926, 0.6834759 ],
       [0.47554502, 0.18260449, 0.22895212]])

In [73]:
np.random.rand(2,2,3)

array([[[0.58614894, 0.18909831, 0.75951309],
        [0.91476154, 0.49580079, 0.17923302]],

       [[0.56938398, 0.64702423, 0.78103389],
        [0.24258182, 0.28714048, 0.04270448]]])

In [74]:
import numpy as np

In [75]:
np.random.seed(0)

In [76]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [77]:
np.random.seed(0)

In [78]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [79]:
np.random.rand()

0.6458941130666561

In [80]:
np.random.rand(5)

array([0.43758721, 0.891773  , 0.96366276, 0.38344152, 0.79172504])

In [86]:
import numpy as np
steps = 2000
draws = np.random.randint(0,2,size = steps)
direction_steps = np.where(draws>0,1,-1)
distance = direction_steps.cumsum()

In [87]:
distance.max()

38

In [88]:
distance.min()

-11

In [89]:
steps = 15/0.5
(np.abs(distance)>=steps).argmax()

689